env:
  global:
    - CC_TEST_REPORTER_ID=21bca6e58da899a0652b337fef9e85a6dec82d9ad017d4fe00bbd4db463e6504
language: node_js
node_js: "node"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test-jest-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT